# Copyright © 2016 Simon McVittie
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

sudo: required
dist: trusty
language: python
cache:
  pip: true
  directories:
    - $HOME/.ccache
install:
  - 'sudo apt-get -qq -y update'
  - >
    sudo apt-get -qq -y install
    autoconf
    automake
    ccache
    dbus
    gnome-desktop-testing
    libdbus-1-dev
    libdbus-glib-1-dev
    libtool
  - >
    test -z "$dbus_ci_system_python" || sudo apt-get -qq -y install
    ${dbus_ci_system_python}
    ${dbus_ci_system_python%-dbg}-docutils
    ${dbus_ci_system_python%-dbg}-gi
  - >
    if test "$dbus_ci_system_python" = python; then
    sudo apt-get -qq -y install python-epydoc python-gobject-2;
    fi
  - >
    wget
    http://httpredir.debian.org/debian/pool/main/a/autoconf-archive/autoconf-archive_20160916-1_all.deb
  - 'sudo dpkg -i autoconf-archive_*_all.deb'
  - 'rm autoconf-archive_*_all.deb'
  - test -n "$dbus_ci_system_python" || pip install tap.py
  - test -z "$dbus_ci_system_python" || deactivate
  - test -z "$dbus_ci_system_python" || pip install --user tap.py
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "nightly"
script:
  - PATH="/usr/lib/ccache:$PATH" ./tools/ci-build.sh

matrix:
  include:
    - python: "2.7"
      env:
        dbus_ci_system_python=python
    - python: "2.7"
      env:
        dbus_ci_system_python=python-dbg
    - python: "3.4"
      env:
        dbus_ci_system_python=python3
    - python: "3.4"
      env:
        dbus_ci_system_python=python3-dbg

# vim:set sw=2 sts=2 et:
